In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier 
heart = pd.read_csv("data/heart-disease.csv")
import numpy as np

In [2]:
heart

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
x = heart.drop("target", axis = 1)

y = heart["target"]

In [4]:
model = RandomForestClassifier()

In [5]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test,y_train,y_test = train_test_split(x, y, test_size = 0.2) 

In [8]:
model.fit(x_train, y_train);

In [9]:
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
114   55    1   1       130   262    0        1      155      0      0.0   
195   59    1   0       170   326    0        0      140      1      3.4   
238   77    1   0       125   304    0        0      162      1      0.0   
279   61    1   0       138   166    0        0      125      1      3.6   
267   49    1   2       118   149    0        0      126      0      0.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
301   57    1   0       130   131    0        1      115      1      1.2   
295   63    1   0       140   187    0        0      144      1      4.0   
276   58    1   0       146   218    0        1      105      0      2.0   
288   57    1   0       110   335    0        1      143      1      3.0   
117   56    1   3       120   193    0        0      162      0      1.9   

     slope  ca  thal  
114      2   0     2  
195      0   0     3  
238      2   3     2  
279      1   1     2  
267      2   3     2  
..     ...  ..   ...  
301      1   1     3  
295      2   2     3  
276      1   1     3  
288      1   1     3  
117      1   0     3  

[242 rows x 13 columns]

In [10]:
y_preds = model.predict(x_test);
y_preds

array([0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1], dtype=int64)

In [11]:
y_test

245    0
169    0
56     1
100    1
26     1
      ..
197    0
262    0
132    1
126    1
182    0
Name: target, Length: 61, dtype: int64

In [12]:
model.score(x_train,y_train)

1.0

In [13]:
model.score(x_test, y_test)

0.8524590163934426

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [15]:
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.81      0.84      0.82        25
           1       0.89      0.86      0.87        36

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61



In [16]:
accuracy_score(y_test, y_preds)

0.8524590163934426

In [17]:
np.random.seed(42)
for i in range(10,100,10):
    print(f"trying model with {i} estimator")
    model = RandomForestClassifier(n_estimators = i).fit(x_train, y_train)
    print(f"Model accuracy on test = {model.score(x_test , y_test) * 100}")
    print("")

trying model with 10 estimator
Model accuracy on test = 80.32786885245902

trying model with 20 estimator
Model accuracy on test = 85.24590163934425

trying model with 30 estimator
Model accuracy on test = 83.60655737704919

trying model with 40 estimator
Model accuracy on test = 85.24590163934425

trying model with 50 estimator
Model accuracy on test = 83.60655737704919

trying model with 60 estimator
Model accuracy on test = 81.9672131147541

trying model with 70 estimator
Model accuracy on test = 86.88524590163934

trying model with 80 estimator
Model accuracy on test = 85.24590163934425

trying model with 90 estimator
Model accuracy on test = 85.24590163934425



In [18]:
import pickle

In [19]:
pickle.dump(model, open("random_forest_model.pkl","wb"))

In [20]:
load_model = pickle.load(open("random_forest_model.pkl", "rb"))

In [21]:
load_model.score(x_test,y_test)

0.8524590163934426

Getting data Ready

In [22]:
x


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [23]:
x_test.shape

(61, 13)

In [24]:
x.shape


(303, 13)

In [25]:
car_sale = pd.read_csv("data/car-sales-extended.csv")

In [26]:
car_sale

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [27]:
x = car_sale.drop("Price", axis = 1)
y = car_sale["Price"]

In [28]:
x_train, x_test,y_train,y_test = train_test_split(x, y, test_size = 0.2) 

In [29]:
from sklearn.ensemble import RandomForestRegressor 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [30]:
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                               remainder = "passthrough"
                               )
tranformed_x = transformer.fit_transform(x)
tranformed_x


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [31]:
pd.DataFrame(tranformed_x)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [32]:
np.random.seed(42)
x_train, x_test,y_train,y_test = train_test_split(tranformed_x, y, test_size = 0.2)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=90)

In [33]:
model.score(x_test,y_test)

0.0

In [34]:
## Missing data



In [35]:
car_sale_missing = pd.read_csv("data/car-sales-extended-missing-data.csv")

In [36]:
car_sale_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [37]:
car_sale_missing
car_sale_missing.dropna(inplace = True)

In [38]:
x = car_sale.drop("Price", axis = 1)
y = car_sale["Price"]

In [39]:
car_sale_missing["Make"].fillna("missing", inplace = True)
car_sale_missing["Colour"].fillna("missing", inplace = True)
car_sale_missing["Odometer (KM)"].fillna(car_sale_missing["Odometer (KM)"].mean(), inplace = True)
car_sale_missing["Doors"].fillna(4, inplace = True)

In [40]:
car_sale_missing.isna().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of       Make  Colour  Odometer (KM)  Doors  Price
0    False   False          False  False  False
1    False   False          False  False  False
2    False   False          False  False  False
3    False   False          False  False  False
4    False   False          False  False  False
..     ...     ...            ...    ...    ...
994  False   False          False  False  False
995  False   False          False  False  False
997  False   False          False  False  False
998  False   False          False  False  False
999  False   False          False  False  False

[773 rows x 5 columns]>

In [41]:
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                               remainder = "passthrough"
                               )
tranformed_x = transformer.fit_transform(x)
tranformed_x


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [42]:
np.random.seed(42)
x_train, x_test,y_train,y_test = train_test_split(tranformed_x, y, test_size = 0.2)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=90)

In [43]:
model.score(x_test,y_test)

0.0

In [44]:
car_sale_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [45]:
np.random.seed(42)
x_train, x_test,y_train,y_test = train_test_split(tranformed_x, y, test_size = 0.2)
model = RandomForestRegressor()
model.fit(x_train, y_train)
model.score(x_test,y_test)


0.3235867221569877